### ISSUE TITLE
Improve handling of resource deletion

### ISSUE THREAD

**Issue by charlie-haley** [charlie-haley/vyconfigure#3]
Currently the handling of resource deletion works, but it leaves behind some mess. When deleting the entire contents of an object, we should ensure the root property is cleaned up.

Example, if we have the following VyConfigure YAML config:
```yaml
ipv6-name:
  WAN_IN:
    default-action: drop
    rule:
      "10":
        action: accept
        state:
          established: enable
          related: enable
      "20": {}
```

Then, we decide we want to delete the rule named "10", then run `vyconfigure plan`, we get the following command output:
```diff
- delete firewall ipv6-name WAN_IN rule 10 action
- delete firewall ipv6-name WAN_IN rule 10 state established
- delete firewall ipv6-name WAN_IN rule 10 state related
```

As we're deleting the entire property and all of its children, the deletion command can simplified to something like this:
```diff
- delete firewall ipv6-name WAN_IN rule 10
```
