### ISSUE TITLE
Lists don't get applied correctly

### ISSUE THREAD

**Issue by charlie-haley** [charlie-haley/vyconfigure#5]
Applying lists doesn't work correctly, if I have the following VyConfigure YAML values and try to add a new item to the list:
```
mdns:
  repeater:
    interface:
    - eth1.10
```
It returns a result like this:
```diff
Changes to be applied:
+ set service mdns repeater interface
```
## Expected
The apply should output something like this:
```diff
Changes to be applied:
+ set service mdns repeater interface eth1.10
```
